//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Defender {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows_Defender.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Антивирус .
        /// </summary>
        internal static string DEF {
            get {
                return ResourceManager.GetString("DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключить антивирус.
        /// </summary>
        internal static string DISABLE_DEFENDER {
            get {
                return ResourceManager.GetString("DISABLE_DEFENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключить брандмауэр.
        /// </summary>
        internal static string DISABLE_FIREWALL {
            get {
                return ResourceManager.GetString("DISABLE_FIREWALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключить защиту.
        /// </summary>
        internal static string DISABLE_PROTECTION {
            get {
                return ResourceManager.GetString("DISABLE_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить антивирус.
        /// </summary>
        internal static string ENABLE_DEFENDER {
            get {
                return ResourceManager.GetString("ENABLE_DEFENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить брандмауэр.
        /// </summary>
        internal static string ENABLE_FIREWALL {
            get {
                return ResourceManager.GetString("ENABLE_FIREWALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить защиту.
        /// </summary>
        internal static string ENABLE_PROTECTION {
            get {
                return ResourceManager.GetString("ENABLE_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брандмауэр .
        /// </summary>
        internal static string FIRE {
            get {
                return ResourceManager.GetString("FIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полная проверка.
        /// </summary>
        internal static string FULL_SCAN {
            get {
                return ResourceManager.GetString("FULL_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отключен.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на включен.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки программы.
        /// </summary>
        internal static string PROGRAM_SETTINGS {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление защитой.
        /// </summary>
        internal static string PROTECTION_CONTROL {
            get {
                return ResourceManager.GetString("PROTECTION_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние защиты:.
        /// </summary>
        internal static string PROTECTION_STATE {
            get {
                return ResourceManager.GetString("PROTECTION_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрая проверка.
        /// </summary>
        internal static string QUICK_SCAN {
            get {
                return ResourceManager.GetString("QUICK_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить проверку.
        /// </summary>
        internal static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки антивируса.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть журнал.
        /// </summary>
        internal static string SHOW_LOG {
            get {
                return ResourceManager.GetString("SHOW_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите для установки параметров....
        /// </summary>
        internal static string UNDEFINED {
            get {
                return ResourceManager.GetString("UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициализация параметра защиты.
        /// </summary>
        internal static string UNDEFINED_MB_CAPTION {
            get {
                return ResourceManager.GetString("UNDEFINED_MB_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для работы программы нужно хотя бы раз включить/отключить защиту в настройках антивируса..
        /// </summary>
        internal static string UNDEFINED_MB_TEXT {
            get {
                return ResourceManager.GetString("UNDEFINED_MB_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить определения.
        /// </summary>
        internal static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить и проверить.
        /// </summary>
        internal static string UPDATE_AND_SCAN {
            get {
                return ResourceManager.GetString("UPDATE_AND_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполняется обновление....
        /// </summary>
        internal static string UPDATE_IN_PROGRESS {
            get {
                return ResourceManager.GetString("UPDATE_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Защитник Windows.
        /// </summary>
        internal static string WINDOWS_DEFENDER {
            get {
                return ResourceManager.GetString("WINDOWS_DEFENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брандмауэр Windows.
        /// </summary>
        internal static string WINDOWS_FIREWALL {
            get {
                return ResourceManager.GetString("WINDOWS_FIREWALL", resourceCulture);
            }
        }
    }
}
